"""Initial schema

Revision ID: 9aac0ccff198
Revises: (none)
Create Date: 2026-10-06 14:12:52.701262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aac0ccff198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conjunto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conjunto_codigo'), ['codigo'], unique=True)

    op.create_table('peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peca_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_peca_codigo_barras'), ['codigo_barras'], unique=True)

    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_codigo'), ['codigo'], unique=True)

    op.create_table('conjunto_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conjunto_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conjunto_id'], ['conjunto.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conjunto_id', 'peca_id', name='uq_conjunto_peca')
    )
    op.create_table('leitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCESSO', 'DUPLICADA', 'FORA_DO_PEDIDO', name='statusleitura'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_necessaria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', 'peca_id', name='uq_pedido_peca')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_item')
    op.drop_table('leitura')
    op.drop_table('conjunto_peca')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_codigo'))

    op.drop_table('pedido')
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peca_codigo_barras'))
        batch_op.drop_index(batch_op.f('ix_peca_codigo'))

    op.drop_table('peca')
    with op.batch_alter_table('conjunto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conjunto_codigo'))

    op.drop_table('conjunto')
    # ### end Alembic commands ###
